-- 코드를 작성해주세요

SELECT CASE
WHEN SUBSTR(DIFFERENTIATION_DATE,6,2) ='01' THEN '1Q'
WHEN SUBSTR(DIFFERENTIATION_DATE,6,2) ='02' THEN '1Q'
WHEN SUBSTR(DIFFERENTIATION_DATE,6,2) ='03' THEN '1Q'
WHEN SUBSTR(DIFFERENTIATION_DATE,6,2) ='04' THEN '2Q'
WHEN SUBSTR(DIFFERENTIATION_DATE,6,2) ='05' THEN '2Q'
WHEN SUBSTR(DIFFERENTIATION_DATE,6,2) ='06' THEN '2Q'
WHEN SUBSTR(DIFFERENTIATION_DATE,6,2) ='07' THEN '3Q'
WHEN SUBSTR(DIFFERENTIATION_DATE,6,2) ='08' THEN '3Q'
WHEN SUBSTR(DIFFERENTIATION_DATE,6,2) ='09' THEN '3Q'
WHEN SUBSTR(DIFFERENTIATION_DATE,6,2) ='10' THEN '4Q'
WHEN SUBSTR(DIFFERENTIATION_DATE,6,2) ='11' THEN '4Q'
WHEN SUBSTR(DIFFERENTIATION_DATE,6,2) ='12' THEN '4Q'
END AS QUARTER, COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA 
GROUP BY QUARTER
ORDER BY QUARTER ASC