-- 코드를 입력하세요
SELECT ANIMAL_ID,NAME
FROM (SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE  ANIMAL_TYPE = 'Dog') AS SUBQUERY 
WHERE NAME LIKE '%El%' OR NAME LIKE '%el%' OR NAME LIKE '%eL%' OR NAME LIKE '%EL%' 
ORDER BY NAME ASC