-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/',C.BOARD_ID,'/',C.FILE_ID,C.FILE_NAME,C.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE C
INNER JOIN (SELECT A.BOARD_ID
FROM USED_GOODS_BOARD A
INNER JOIN (SELECT BOARD_ID,MAX(VIEWS) AS MAXVIEWS
FROM USED_GOODS_BOARD 
GROUP BY BOARD_ID ORDER BY MAXVIEWS DESC
LIMIT 1) B ON A.BOARD_ID = B.BOARD_ID) D ON C.BOARD_ID = D.BOARD_ID
ORDER BY C.FILE_ID DESC