-- 코드를 작성해주세요

SELECT SUM(A.SCORE) AS SCORE ,A.EMP_NO, B.EMP_NAME,B.POSITION,B.EMAIL
FROM HR_GRADE A
INNER JOIN HR_EMPLOYEES B ON A.EMP_NO = B.EMP_NO
GROUP BY A.YEAR, A.EMP_NO
HAVING A.YEAR = '2022'
ORDER BY SCORE DESC
LIMIT 1