-- 코드를 작성해주세요
SELECT A.ITEM_ID,A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
LEFT JOIN(
SELECT PARENT_ITEM_ID, COUNT(*) AS PARENTCOUNT
FROM ITEM_TREE 
WHERE PARENT_ITEM_ID IS NOT NULL
GROUP BY PARENT_ITEM_ID) B ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE B.PARENTCOUNT IS NULL
ORDER BY ITEM_ID DESC

