-- 코드를 작성해주세요
SELECT A.ID, CASE 
WHEN B.COUNT IS NULL THEN 0
WHEN B.COUNT IS NOT NULL THEN B.COUNT
END AS CHILD_COUNT
FROM ECOLI_DATA A
LEFT JOIN (
SELECT PARENT_ID,COUNT(PARENT_ID) AS COUNT
FROM ECOLI_DATA 
GROUP BY PARENT_ID 
HAVING PARENT_ID IS NOT NULL    
) B ON A.ID = B. PARENT_ID
ORDER BY A.ID ASC