-- 코드를 작성해주세요

SELECT COUNT(*) AS FISH_COUNT

FROM FISH_INFO 

INNER JOIN FISH_NAME_INFO  ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO. FISH_TYPE

WHERE FISH_INFO.FISH_TYPE IN(
    SELECT FISH_NAME_INFO.FISH_TYPE 
    FROM FISH_NAME_INFO 
    WHERE FISH_NAME = 'BASS' OR FISH_NAME= 'SNAPPER' 
)